// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var File = exports.File = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Request = exports.Request = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Unrequest = exports.Unrequest = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Queued = exports.Queued = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Refuse = exports.Refuse = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Header = exports.Header = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Data = exports.Data = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineFile()
defineRequest()
defineUnrequest()
defineQueued()
defineRefuse()
defineHeader()
defineData()

function defineFile () {
  File.encodingLength = encodingLength
  File.encode = encode
  File.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.sha256)) {
      var len = encodings.bytes.encodingLength(obj.sha256)
      length += 1 + len
    }
    if (defined(obj.start)) {
      var len = encodings.varint.encodingLength(obj.start)
      length += 1 + len
    }
    if (defined(obj.length)) {
      var len = encodings.varint.encodingLength(obj.length)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.sha256)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.sha256, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.start)) {
      buf[offset++] = 16
      encodings.varint.encode(obj.start, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.length)) {
      buf[offset++] = 24
      encodings.varint.encode(obj.length, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      sha256: null,
      start: 0,
      length: 0
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.sha256 = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.start = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 3:
        obj.length = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineRequest () {
  Request.encodingLength = encodingLength
  Request.encode = encode
  Request.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.files)) {
      for (var i = 0; i < obj.files.length; i++) {
        if (!defined(obj.files[i])) continue
        var len = File.encodingLength(obj.files[i])
        length += varint.encodingLength(len)
        length += 1 + len
      }
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.files)) {
      for (var i = 0; i < obj.files.length; i++) {
        if (!defined(obj.files[i])) continue
        buf[offset++] = 10
        varint.encode(File.encodingLength(obj.files[i]), buf, offset)
        offset += varint.encode.bytes
        File.encode(obj.files[i], buf, offset)
        offset += File.encode.bytes
      }
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      files: []
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.files.push(File.decode(buf, offset, offset + len))
        offset += File.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineUnrequest () {
  Unrequest.encodingLength = encodingLength
  Unrequest.encode = encode
  Unrequest.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.files)) {
      for (var i = 0; i < obj.files.length; i++) {
        if (!defined(obj.files[i])) continue
        var len = File.encodingLength(obj.files[i])
        length += varint.encodingLength(len)
        length += 1 + len
      }
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.files)) {
      for (var i = 0; i < obj.files.length; i++) {
        if (!defined(obj.files[i])) continue
        buf[offset++] = 10
        varint.encode(File.encodingLength(obj.files[i]), buf, offset)
        offset += varint.encode.bytes
        File.encode(obj.files[i], buf, offset)
        offset += File.encode.bytes
      }
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      files: []
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.files.push(File.decode(buf, offset, offset + len))
        offset += File.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineQueued () {
  Queued.encodingLength = encodingLength
  Queued.encode = encode
  Queued.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.queuePosition)) throw new Error("queuePosition is required")
    var len = encodings.varint.encodingLength(obj.queuePosition)
    length += 1 + len
    if (defined(obj.queueBytes)) {
      var len = encodings.varint.encodingLength(obj.queueBytes)
      length += 1 + len
    }
    if (defined(obj.queueFiles)) {
      var len = encodings.varint.encodingLength(obj.queueFiles)
      length += 1 + len
    }
    if (defined(obj.files)) {
      for (var i = 0; i < obj.files.length; i++) {
        if (!defined(obj.files[i])) continue
        var len = File.encodingLength(obj.files[i])
        length += varint.encodingLength(len)
        length += 1 + len
      }
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.queuePosition)) throw new Error("queuePosition is required")
    buf[offset++] = 8
    encodings.varint.encode(obj.queuePosition, buf, offset)
    offset += encodings.varint.encode.bytes
    if (defined(obj.queueBytes)) {
      buf[offset++] = 16
      encodings.varint.encode(obj.queueBytes, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.queueFiles)) {
      buf[offset++] = 24
      encodings.varint.encode(obj.queueFiles, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.files)) {
      for (var i = 0; i < obj.files.length; i++) {
        if (!defined(obj.files[i])) continue
        buf[offset++] = 34
        varint.encode(File.encodingLength(obj.files[i]), buf, offset)
        offset += varint.encode.bytes
        File.encode(obj.files[i], buf, offset)
        offset += File.encode.bytes
      }
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      queuePosition: 0,
      queueBytes: 0,
      queueFiles: 0,
      files: []
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.queuePosition = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        found0 = true
        break
        case 2:
        obj.queueBytes = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 3:
        obj.queueFiles = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 4:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.files.push(File.decode(buf, offset, offset + len))
        offset += File.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineRefuse () {
  Refuse.encodingLength = encodingLength
  Refuse.encode = encode
  Refuse.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.files)) {
      for (var i = 0; i < obj.files.length; i++) {
        if (!defined(obj.files[i])) continue
        var len = File.encodingLength(obj.files[i])
        length += varint.encodingLength(len)
        length += 1 + len
      }
    }
    if (defined(obj.reason)) {
      var len = encodings.varint.encodingLength(obj.reason)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.files)) {
      for (var i = 0; i < obj.files.length; i++) {
        if (!defined(obj.files[i])) continue
        buf[offset++] = 10
        varint.encode(File.encodingLength(obj.files[i]), buf, offset)
        offset += varint.encode.bytes
        File.encode(obj.files[i], buf, offset)
        offset += File.encode.bytes
      }
    }
    if (defined(obj.reason)) {
      buf[offset++] = 16
      encodings.varint.encode(obj.reason, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      files: [],
      reason: 0
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.files.push(File.decode(buf, offset, offset + len))
        offset += File.decode.bytes
        break
        case 2:
        obj.reason = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineHeader () {
  Header.encodingLength = encodingLength
  Header.encode = encode
  Header.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.filename)) {
      var len = encodings.string.encodingLength(obj.filename)
      length += 1 + len
    }
    if (defined(obj.sha256)) {
      var len = encodings.bytes.encodingLength(obj.sha256)
      length += 1 + len
    }
    if (defined(obj.size)) {
      var len = encodings.varint.encodingLength(obj.size)
      length += 1 + len
    }
    if (defined(obj.offset)) {
      var len = encodings.varint.encodingLength(obj.offset)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.filename)) {
      buf[offset++] = 42
      encodings.string.encode(obj.filename, buf, offset)
      offset += encodings.string.encode.bytes
    }
    if (defined(obj.sha256)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.sha256, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.size)) {
      buf[offset++] = 32
      encodings.varint.encode(obj.size, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.offset)) {
      buf[offset++] = 24
      encodings.varint.encode(obj.offset, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      filename: "",
      sha256: null,
      size: 0,
      offset: 0
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 5:
        obj.filename = encodings.string.decode(buf, offset)
        offset += encodings.string.decode.bytes
        break
        case 2:
        obj.sha256 = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 4:
        obj.size = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 3:
        obj.offset = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineData () {
  Data.encodingLength = encodingLength
  Data.encode = encode
  Data.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.data)) throw new Error("data is required")
    var len = encodings.bytes.encodingLength(obj.data)
    length += 1 + len
    if (defined(obj.offset)) {
      var len = encodings.varint.encodingLength(obj.offset)
      length += 1 + len
    }
    if (defined(obj.chunkNumber)) {
      var len = encodings.varint.encodingLength(obj.chunkNumber)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.data)) throw new Error("data is required")
    buf[offset++] = 10
    encodings.bytes.encode(obj.data, buf, offset)
    offset += encodings.bytes.encode.bytes
    if (defined(obj.offset)) {
      buf[offset++] = 24
      encodings.varint.encode(obj.offset, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.chunkNumber)) {
      buf[offset++] = 48
      encodings.varint.encode(obj.chunkNumber, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      data: null,
      offset: 0,
      chunkNumber: 0
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.data = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        found0 = true
        break
        case 3:
        obj.offset = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 6:
        obj.chunkNumber = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
